var app = angular.module('app', [ 'pascalprecht.translate' ]);

app.config(function($translateProvider) {
	$translateProvider.translations('en', {
		NAME : 'Name',
		CALL : 'Calls',
		TOTAL : 'Total',
		MIN : 'Min',
		MAX : 'Max',
		AVG : 'Avg',
		DURATION : 'Duration',
		STATE : 'State',
		COMMENT : 'Comments',
		TOTALNUMBER : 'Total number',
		TOTALSUCCED : 'Total success',
		ERRORRATIO : 'Error ratio',
		MINDURATION : 'Min duration',
		MAXDURATION : 'Max duration',
		AVGDURATION : 'Avg duration',
		NBOPENED : 'Open',
		FREE_MEMORY : 'Free memory (Mb)',
		TOTAL_MEMORY : 'Total memory (Mb)',
		USED_MEMORY : 'Used memory (Mb)',
		JVM_UPTIME : 'JVM Uptime',
		JVM_VENDOR : 'JVM Vendor',
		JVM_VERSION : 'JVM Version',
		OS_NAME : 'OS Name',
		OS_ARCH : 'OS Architecture',
		OS_VERSION : 'OS Version',
		BUILD_VERSION : 'Build Version',
		BUILD_DATE : 'Build Date',
		BUILD_REVISION : 'Build Revision',
		INDICATOR_TITLE : 'Indicator informations',
		REQUEST_TITLE : 'HTTP requests informations',
		REQUEST_SUBTITLE1 : 'Number of requests',
		REQUEST_SUBTITLE2 : 'Error rate',
		REQUEST_LABEL1 : 'HTTP request',
		REQUEST_LABEL2 : 'Request error',
		SESSION_TITLE : 'Information sessions',
		SESSION_SUBTITLE1 : 'Opening and closing',
		SESSION_LABEL1 : 'Login',
		SESSION_LABEL2 : 'Logoff',
		RESOURCE_TITLE : 'External resource informations',
		RESOURCE_SUBTITLE1 : 'Execution time',
		RESOURCE_SUBTITLE2 : 'Back in error',
		DAY : 'Day',
		WEEK : 'Week',
		MONTH : 'Month',
	});

	$translateProvider.translations('fr', {
		NAME : 'Nom',
		CALL : 'Appels',
		TOTAL : 'Total',
		MIN : 'Min',
		MAX : 'Max',
		AVG : 'Moy',
		DURATION : 'Durée',
		STATE : 'Etat',
		COMMENT : 'Commentaires',
		TOTALNUMBER : 'Nombre total',
		TOTALSUCCED : 'Succès',
		ERRORRATIO : 'Ratio d\'erreur',
		MINDURATION : 'Durée minimum',
		MAXDURATION : 'Durée maximum',
		AVGDURATION : 'Durée moyenne',
		NBOPENED : 'Ouverte',
		FREE_MEMORY : 'Mémoire libre (Mo)',
		TOTAL_MEMORY : 'Mémoire total (Mo)',
		USED_MEMORY : 'Mémoire utilisé (Mo)',
		JVM_UPTIME : 'Execution JVM',
		JVM_VENDOR : 'Fournisseur JVM',
		JVM_VERSION : 'Version JVM',
		OS_NAME : 'Nom de l\'OS',
		OS_ARCH : 'Architecture de l\'OS',
		OS_VERSION : 'Version de l\'OS',
		BUILD_VERSION : 'Version du livrable',
		BUILD_DATE : 'Date de construction',
		BUILD_REVISION : 'Revision du livrable',
		INDICATOR_TITLE : 'Informations sur un indicateur',
		REQUEST_TITLE : 'Informations sur les requêtes HTTP',
		REQUEST_SUBTITLE1 : 'Nombre de requête',
		REQUEST_SUBTITLE2 : 'Taux d\'erreur',
		REQUEST_LABEL1 : 'Requête HTTP',
		REQUEST_LABEL2 : 'Requête en erreur',
		SESSION_TITLE : 'Informations sur les sessions',
		SESSION_SUBTITLE1 : 'Ouverture et fermeture',
		SESSION_LABEL1 : 'Ouverture de session',
		SESSION_LABEL2 : 'Fermeture de session',
		RESOURCE_TITLE : 'Informations sur une resource externe',
		RESOURCE_SUBTITLE1 : 'Temps d\'execution',
		RESOURCE_SUBTITLE2 : 'Retour en erreur',
		DAY : 'Jour',
		WEEK : 'Semaine',
		MONTH : 'Mois',
	});

	$translateProvider.translations('de', {
		NAME : 'Name',
		CALL : 'Anrufe',
		TOTAL : 'Summe',
		MIN : 'Min',
		MAX : 'Max',
		AVG : 'Durchschnitt',
		DURATION : 'Dauer',
		STATE : 'Zustand',
		COMMENT : 'Comments',
		TOTALNUMBER : 'Gesamtzahl',
		TOTALSUCCED : 'Erfolg',
		ERRORRATIO : 'Fehler-Verhältnis',
		MINDURATION : 'Dauer minimum',
		MAXDURATION : 'Dauer maximum',
		AVGDURATION : 'Dauer Durchschnitt',
		NBOPENED : 'Geöffnet',
		FREE_MEMORY : 'Freier Speicher(Mb)',
		TOTAL_MEMORY : 'Total Speicher (Mb)',
		USED_MEMORY : 'Gebrauchte Speicher (Mb)',
		JVM_UPTIME : 'Ausführung JVM',
		JVM_VENDOR : 'Versorger JVM',
		JVM_VERSION : 'Version JVM',
		OS_NAME : 'OS Name',
		OS_ARCH : 'OS Architektur',
		OS_VERSION : 'OS Version',
		BUILD_VERSION : 'verfügbar Version',
		BUILD_DATE : 'Herstellungsdatum',
		BUILD_REVISION : 'Build Revision',
		INDICATOR_TITLE : 'Informationen auf einer Anzeige',
		REQUEST_TITLE : 'HTTP fordert Informationen',
		REQUEST_SUBTITLE1 : 'Anzahl der Anfragen',
		REQUEST_SUBTITLE2 : 'Fehler-Verhältnis',
		REQUEST_LABEL1 : 'HTTP Request',
		REQUEST_LABEL2 : 'Anwendungsfehler',
		SESSION_TITLE : 'Informationsveranstaltungen',
		SESSION_SUBTITLE1 : 'Öffnen und Schließen',
		SESSION_LABEL1 : 'Login',
		SESSION_LABEL2 : 'Logoff',
		RESOURCE_TITLE : 'Informationen zu einer externen Quelle',
		RESOURCE_SUBTITLE1 : 'Ausführungszeit',
		RESOURCE_SUBTITLE2 : 'Zurück in Fehler',
		DAY : 'Tag',
		WEEK : 'Woche',
		MONTH : 'Monat',
	});
	
	var lang = sessionStorage.getItem('lang');

	if (lang == null) {
		lang = 'en';
	}

	$translateProvider.preferredLanguage(lang);
});